name: Build installer for supported os
on: push

jobs:
  build-app:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Build the application
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: ./mvnw install
      - run: mkdir staging && cp app/build/installer/* staging
      - name: upload build result
        uses: actions/upload-artifact@v2
        with:
          name: PPM_1.0.5-${{matrix.os}}
          path: staging